name: CODE - Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis-code.yml"

jobs:
  jarvis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check GitHub Status
        run: |
          # 使用curl和jq直接调用GitHub Status API，避免依赖第三方Action
          STATUS=$(curl -s https://www.githubstatus.com/api/v2/status.json | jq -r '.status.description')
          echo "GitHub Status: $STATUS"
          # 可选：根据需求添加后续逻辑（如状态检查）
